name: Deploy docker image to ghcr

# Deploy docker image to ghcr on pushes to master and all releases/tags.
# Note releases to docker hub are managed separately in another process
# (github sends webhooks to docker hub which triggers the build there).
# This workflow is an alternative form of retention for docker images
# which also allows us to tag and retain every single commit to master.

on:
  push:
    branches:
      - master
  release:
    types: [released]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  deploy-ghcr:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
            # need to fetch unshallow so that setuptools_scm can infer the version
            fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        name: Install python
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Generate vyper/version.py
        run: |
          pip install .
          echo "VYPER_VERSION=$(PYTHONPATH=. python vyper/cli/vyper_compile.py --version)" >> "$GITHUB_ENV"

      - name: generate tag suffix
        if: ${{ github.event_name != 'release' }}
        run: echo "VERSION_SUFFIX=-dev" >> "$GITHUB_ENV"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=${{ env.VYPER_VERSION }}${{ env.VERSION_SUFFIX }}
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}


      - name: Login to ghcr.io
        uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: step-security/docker-build-push-action@a8c3d08b23f8be6aeed43eb1a14ce6fe51284438 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
